- name: Configure Cisco Router Interface
  hosts: cisco_r
  become: true
  tasks:
          - name: Setting IP  address for interface0/0
            cisco.ios.ios_config:
                    lines:
                            - ip address 192.168.1.2 255.255.255.0
                            - no shutdown
                    parents: interface fastethernet 0/0          
          - name: conf top level conf 
            cisco.ios.ios_config:
                    lines: hostname "router1"

