---
- name: Configuring Apache Web Server
  hosts: linux_servers
  become: true
  tasks:
          - name: Install nginx  Packages
            apt:
                    name: nginx
                    state: present
            tags: 
            - pack_install

          - name: Start nginx service
            service:
                name: nginx
                state: started
            tags: 
            - start_nginx

          - name: Add Firewall Rules
            firewalld:
                    port: 80/tcp
                    permanent: true
                    state: enabled
            tags: 
            - add-fire

          - name: Reload Firewall config for 
            systemd:
                    name: firewalld
                    state: reloaded

            tags: 
            - rel-fire

          - name: copy Index File to Apache
            copy:
                    src: /tmp/indx.html
                    dest: /var/www/html/
            tags: 
            - cp_file

          - name: Restart nginx Service
            service:
                    name: nginx
                    state: restarted
            tags: 
            - rest_nginx
              


# We use tags to specify plays when we execute the playbook               
